export { default as Menu } from './Menu/Menu'
export { default as SkillItem } from './SkillItem/SkillItem'
export { default as Socials } from './Socials/Socials'
export { default as TextureSvg } from './TextureSvg/TextureSvg'
export { default as SectionHeading } from './SectionHeading/SectionHeading'
export { default as Footer } from './Footer/Footer'