export { default as SkillItem } from "./SkillItem/SkillItem"
export { default as Socials } from "./Socials/Socials"
export { default as TextureSvg } from "./TextureSvg/TextureSvg"
export { default as SectionHeading } from "./SectionHeading/SectionHeading"
export { default as Footer } from "./Footer/Footer"
export { default as Project } from "./Project/Project"
export { default as ScrollToTop } from "./ScrollToTop"
